
version: '3.3'

services:
  cit-web:
    image: 'node:14'
    volumes:
      - ./cit-web:/code
    working_dir: /code/
    networks:
      - back-tier
  web:
    build: ./web
    image: countable/cit
    volumes:
      - ./web:/code
      - static:/static
    networks:
      - back-tier
    environment:
      - AUTHORITY=https://login.microsoftonline.com/
      - SCOPE=https://analysis.windows.net/powerbi/api/.default
      - TENANT_ID=${TENANT_ID}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - ROUTE_PLANNER_API_KEY=${ROUTE_PLANNER_API_KEY}
  db:
    image: mdillon/postgis
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - back-tier

  nginx:
    networks:
      - back-tier
    image: nginx:1.13
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static

volumes:
  pg-data:
    driver: local
  static:
    driver: local

networks:
  back-tier:
    driver: bridge
