
version: '3.3'

services:
  cit-web:
    image: 'node'
    volumes:
      - ./cit-web:/code
    working_dir: /code/
  web:
    build: ./web
    ports:
      - 8000:8000
    volumes:
      - ./web:/code
      - static:/static
    networks:
      - back-tier
    environment:
      - TENANT_ID=04bb63e9-2141-43c1-95a7-5595ef09761a
      - CLIENT_ID=55b92cf4-c773-4b33-be8d-101cbb1d678e
      - AUTHORITY=https://login.microsoftonline.com/
      - SCOPE=https://analysis.windows.net/powerbi/api/.default
      - CLIENT_SECRET=U3Oc_oTHI-d1CR0UR.6XNU35~q19zaHcnv
  db:
    image: mdillon/postgis
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - back-tier

  nginx:
    networks:
      - back-tier
    ports:
      - 80:80
    image: nginx:1.13
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d
     - static:/static

volumes:
  pg-data:
    driver: local
  static:
    driver: local

networks:
  back-tier:
    driver: bridge
