version: "3.3"

services:
  cit-web:
    container_name: cit-web
    build: ./cit3.0-web
    env_file:
      - cit3.0-web/.env
    restart: always
    ports:
      - "80:80"
  cit-api:
    build: 
      context: ./cit-api
      dockerfile: Dockerfile.dev
    image: countable/cit
    volumes:
      - ./cit-api:/code
      - static:/static
      - media:/media
    env_file:
      - cit-api/.env
    ports:
      - 8000:8000
    depends_on: 
      - db
  db:
    image: mdillon/postgis
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db:/code
    ports:
      - 5432:5432

  kcpostgres:
    image: postgres
    volumes:
      - kc-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      volumes:
        - ./realm-export.json:/tmp/realm-export.json
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: kcpostgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        KEYCLOAK_IMPORT: /tmp/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
        
      ports:
        - 8080:8080
      depends_on:
        - kcpostgres
  keycloak-config:
    build:
      context: .
      args:
        - KEYCLOAK_URL=http://localhost:8080
    command: sh -c "dockerize -wait http://localhost:8080/auth -timeout 300s /tmp/createuser.sh"
    depends_on: [keycloak]

volumes:
  pg-data:
    driver: local
  kc-pg-data:
    driver: local
  static:
    driver: local
  media:
    driver: local
