kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app_name }}-api
  labels:
    app: {{ .Values.app_name }}-api
    name: {{ .Values.app_name }}-api
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.app_name }}-api
    weight: 100
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app_name }}-web
  labels:
    app: {{ .Values.app_name }}-web
    name: {{ .Values.app_name }}-web
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.app_name }}-web
    weight: 100
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app_name }}-patroni
  labels:
    app: {{ .Values.app_name }}-patroni
    name: {{ .Values.app_name }}-patroni
spec:
  port:
    targetPort: 5432-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.app_name }}-patroni
    weight: 100
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: b4e935-dev
  labels:
    app: {{ .Values.app_name }}-patroniexternal
    name: {{ .Values.app_name }}-patroniexternal
spec:
  host: dev.communityinformationtool.gov.bc.ca
  to:
    kind: Service
    name: {{ .Values.app_name }}-web
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
