# This workflow will build and push a new container image to Azure ACR in the Cit01-Test Resource Group

on:
  push:
    branches:
      - develop
  workflow_dispatch:

name: Build and Push (Cit01-Test RG)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: "Build and push webapi"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER_TEST }}
          username: ${{ secrets.REGISTRY_USERNAME_TEST }}
          password: ${{ secrets.REGISTRY_PASSWORD_TEST }}
      # TODO: tags with ${{ github.sha }}
      - run: |
          docker build cit-api -t ${{ secrets.REGISTRY_LOGIN_SERVER_TEST }}/cit-webapi:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER_TEST }}/cit-webapi:latest

      - name: "Build and push frontend"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER_TEST }}
          username: ${{ secrets.REGISTRY_USERNAME_TEST }}
          password: ${{ secrets.REGISTRY_PASSWORD_TEST }}
      - run: |
          docker build cit3.0-web -t ${{ secrets.REGISTRY_LOGIN_SERVER_TEST }}/cit-frontend:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER_TEST }}/cit-frontend:latest
