# This workflow will build and push a new data pipeline image to Openshift Image Stream Tools
name: Backend Build and Push (Test)

on:
  push:
    branches: [openshift]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
      
      - name: "Build pipeline image"
        run: |
          docker build cit-api -t image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/cit-data-pipeline:develop -f Dockerfile.pipeline
      
      - name: "Push backend to Openshift" 
        uses: docker/login-action@v2
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: serviceaccount
          password: ${{ secrets.OCP_REGISTRY_PASSWORD }}
      - run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/cit-data-pipeline:develop