# This workflow will build and push a new data pipeline container image to the Openshift Image Stream Tools
name: Data Pipeline Build and Push

on:
  push:
    branches: [openshift]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
      
      - name: "Build data pipeline"
        run: |
          docker-compose build data-pipeline
          docker tag data-pipeline image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/data-pipeline:develop
      
      - name: "Push data pipeline to Openshift" 
        uses: docker/login-action@v2
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: serviceaccount
          password: ${{ secrets.OCP_REGISTRY_PASSWORD }}
      - run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/data-pipeline:develop